
package gr.gsis.rgwspublic.rgwspublic;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "RgWsPublic", targetNamespace = "http://gr/gsis/rgwspublic/RgWsPublic.wsdl", wsdlLocation = "https://www1.gsis.gr:443/webtax2/wsgsis/RgWsPublic/RgWsPublicPort?WSDL")
public class RgWsPublic_Service
    extends Service
{

    private final static URL RGWSPUBLIC_WSDL_LOCATION;
    private final static WebServiceException RGWSPUBLIC_EXCEPTION;
    private final static QName RGWSPUBLIC_QNAME = new QName("http://gr/gsis/rgwspublic/RgWsPublic.wsdl", "RgWsPublic");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://www1.gsis.gr:443/webtax2/wsgsis/RgWsPublic/RgWsPublicPort?WSDL");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        RGWSPUBLIC_WSDL_LOCATION = url;
        RGWSPUBLIC_EXCEPTION = e;
    }

    public RgWsPublic_Service() {
        super(__getWsdlLocation(), RGWSPUBLIC_QNAME);
    }

    public RgWsPublic_Service(WebServiceFeature... features) {
        super(__getWsdlLocation(), RGWSPUBLIC_QNAME, features);
    }

    public RgWsPublic_Service(URL wsdlLocation) {
        super(wsdlLocation, RGWSPUBLIC_QNAME);
    }

    public RgWsPublic_Service(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, RGWSPUBLIC_QNAME, features);
    }

    public RgWsPublic_Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public RgWsPublic_Service(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns RgWsPublic
     */
    @WebEndpoint(name = "RgWsPublicPort")
    public RgWsPublic getRgWsPublicPort() {
        return super.getPort(new QName("http://gr/gsis/rgwspublic/RgWsPublic.wsdl", "RgWsPublicPort"), RgWsPublic.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns RgWsPublic
     */
    @WebEndpoint(name = "RgWsPublicPort")
    public RgWsPublic getRgWsPublicPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://gr/gsis/rgwspublic/RgWsPublic.wsdl", "RgWsPublicPort"), RgWsPublic.class, features);
    }

    private static URL __getWsdlLocation() {
        if (RGWSPUBLIC_EXCEPTION!= null) {
            throw RGWSPUBLIC_EXCEPTION;
        }
        return RGWSPUBLIC_WSDL_LOCATION;
    }

}
